# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ahrtodorn' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ahrtodorn
  platform :ios, '9.0'
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'

  target 'ahrtodorn-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ahrtodornTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ahrtodorn-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ahrtodorn-tvOS

end
